@extends('layouts.app')
@section('title','Prepare Assignment')
@section('heading','Prepare asset assignment')
@section('content')
<div class="mx-auto max-w-4xl pt-4"><form method="POST" action="{{ route('assignments.store') }}" class="space-y-6">@csrf
@if($errors->any())<div class="rounded-xl border border-red-200 bg-red-50 px-5 py-4 text-sm text-red-700"><ul class="list-disc pl-5">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
<section class="eims-card p-6"><p class="text-xs font-bold uppercase tracking-wider text-emerald-500">Procurement allocation</p><h2 class="mt-1 text-xl font-black text-eims-ink">Asset and recipient</h2><p class="mt-2 text-sm text-slate-400">The asset becomes reserved immediately. Ownership changes only after recipient confirmation.</p><div class="mt-6 grid gap-5 md:grid-cols-2">
<fieldset class="md:col-span-2"><legend class="text-sm font-bold">Assignment type *</legend><div class="mt-2 flex gap-3"><label class="rounded-xl border px-4 py-3"><input type="radio" name="assignment_type" value="individual" checked> Individual officer</label><label class="rounded-xl border px-4 py-3"><input type="radio" name="assignment_type" value="department"> Department</label></div></fieldset>
<div><label class="text-sm font-bold text-slate-600">Available asset *</label><select name="asset_id" required class="mt-2 w-full rounded-xl border border-slate-200 px-4 py-3 text-sm"><option value="">Select asset</option>@foreach($assets as $asset)<option value="{{ $asset->id }}" @selected(old('asset_id',$selectedAsset?->id)==$asset->id)>{{ $asset->asset_tag }} · {{ $asset->name }}</option>@endforeach</select></div>
<div data-individual><label class="text-sm font-bold text-slate-600">Recipient officer *</label><select name="assigned_to_user_id" class="mt-2 w-full rounded-xl border border-slate-200 px-4 py-3 text-sm"><option value="">Select officer</option>@foreach($users as $user)<option value="{{ $user->id }}" @selected(old('assigned_to_user_id')==$user->id)>{{ $user->name }} · {{ $user->staff_number }}</option>@endforeach</select></div>
<div data-department class="hidden"><label class="text-sm font-bold text-slate-600">Department *</label><select name="assigned_to_department_id" class="mt-2 w-full rounded-xl border border-slate-200 px-4 py-3 text-sm"><option value="">Select department</option>@foreach($departments as $department)<option value="{{ $department->id }}">{{ $department->name }}</option>@endforeach</select></div>
<div data-department class="hidden md:col-span-2"><label class="text-sm font-bold text-slate-600">Authorized receiving officers *</label><div class="mt-2 grid gap-2 sm:grid-cols-2">@foreach($users as $user)<label data-user-department="{{ $user->department_id }}" class="receiver hidden rounded-xl border p-3 text-sm"><input type="checkbox" name="authorized_receiver_ids[]" value="{{ $user->id }}"> {{ $user->name }} · {{ $user->staff_number }}</label>@endforeach</div><p class="mt-2 text-xs text-slate-400">Any selected officer may confirm on behalf of the department; the first confirmation closes the handover.</p></div>
<div><label class="text-sm font-bold text-slate-600">Receiving location *</label><select name="location_id" required class="mt-2 w-full rounded-xl border border-slate-200 px-4 py-3 text-sm"><option value="">Select location</option>@foreach($locations as $location)<option value="{{ $location->id }}" @selected(old('location_id')==$location->id)>{{ $location->name }}</option>@endforeach</select></div>
<div><label class="text-sm font-bold text-slate-600">Condition at issue *</label><select name="condition_at_issue" required class="mt-2 w-full rounded-xl border border-slate-200 px-4 py-3 text-sm">@foreach(['excellent','good','fair','damaged'] as $condition)<option value="{{ $condition }}" @selected(old('condition_at_issue','good')===$condition)>{{ ucfirst($condition) }}</option>@endforeach</select></div>
<div><label class="text-sm font-bold text-slate-600">Expected return date</label><input type="date" name="expected_return_at" value="{{ old('expected_return_at') }}" class="mt-2 w-full rounded-xl border border-slate-200 px-4 py-3 text-sm"></div>
<div class="md:col-span-2"><label class="text-sm font-bold text-slate-600">Assignment purpose *</label><textarea name="purpose" required maxlength="500" rows="3" class="mt-2 w-full rounded-xl border border-slate-200 px-4 py-3 text-sm" placeholder="Explain why this property is being assigned">{{ old('purpose') }}</textarea></div>
<div class="md:col-span-2"><label class="text-sm font-bold text-slate-600">Issue notes</label><textarea name="issue_notes" rows="2" class="mt-2 w-full rounded-xl border border-slate-200 px-4 py-3 text-sm">{{ old('issue_notes') }}</textarea></div>
</div></section>
<section class="eims-card p-6"><div class="flex items-center justify-between gap-4"><div><h2 class="font-extrabold text-eims-ink">Included accessories</h2><p class="mt-1 text-xs text-slate-400">Record chargers, keys, cables or other items handed over.</p></div><button type="button" data-add-accessory class="rounded-xl border border-indigo-200 bg-indigo-50 px-4 py-2 text-sm font-bold text-indigo-600">＋ Add accessory</button></div><div data-accessory-list class="mt-4 space-y-2"></div></section>
<div class="flex justify-end gap-3"><a href="{{ route('assignments.index') }}" class="rounded-xl border border-slate-200 px-5 py-3 text-sm font-bold text-slate-500">Cancel</a><button class="rounded-xl bg-gradient-to-r from-emerald-500 to-teal-600 px-6 py-3 text-sm font-extrabold text-white shadow-lg">Reserve and prepare handover</button></div>
</form></div>
<script>(()=>{const list=document.querySelector('[data-accessory-list]');let i=0;function add(value=''){list.insertAdjacentHTML('beforeend',`<div class="flex gap-2"><input name="accessories[${i++}]" value="${String(value).replace(/[&<>"]/g,'')}" pattern="[A-Za-z0-9 ]+" class="flex-1 rounded-xl border border-slate-200 px-4 py-2.5 text-sm" placeholder="e.g. Laptop Charger"><button type="button" class="rounded-xl px-3 text-red-500" onclick="this.parentElement.remove()">Remove</button></div>`)}document.querySelector('[data-add-accessory]').addEventListener('click',()=>add());Object.values(@json(old('accessories',[]))).forEach(add);const radios=document.querySelectorAll('[name=assignment_type]'),individual=document.querySelector('[data-individual]'),department=document.querySelectorAll('[data-department]'),deptSelect=document.querySelector('[name=assigned_to_department_id]');function update(){const type=document.querySelector('[name=assignment_type]:checked').value;individual.classList.toggle('hidden',type!=='individual');department.forEach(el=>el.classList.toggle('hidden',type!=='department'));}function receivers(){document.querySelectorAll('.receiver').forEach(el=>{const show=el.dataset.userDepartment===deptSelect.value;el.classList.toggle('hidden',!show);if(!show)el.querySelector('input').checked=false;});}radios.forEach(r=>r.addEventListener('change',update));deptSelect.addEventListener('change',receivers);update();receivers()})();</script>
@endsection
