@extends('layouts.app')
@section('title','Assignments')
@section('heading','Asset assignments')
@section('content')
<div class="pt-4">
    @if(session('success'))<div class="mb-5 rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm font-bold text-emerald-700">{{ session('success') }}</div>@endif
    <section class="eims-card overflow-hidden">
        <div class="flex flex-col gap-4 border-b border-slate-100 p-5 lg:flex-row lg:items-center"><div><h2 class="font-extrabold text-eims-ink">Assignment register</h2><p class="mt-1 text-xs text-slate-400">Prepared, accepted and rejected property handovers.</p></div><form method="GET" class="eims-filter-panel ml-auto grid gap-3 sm:grid-cols-3 sm:items-end"><label class="eims-filter-label">Search<input name="search" value="{{ request('search') }}" placeholder="Asset, tag or recipient" class="eims-filter-field min-w-52"></label><label class="eims-filter-label">Assignment type<select name="type" class="eims-filter-field"><option value="">All types</option><option value="individual" @selected(request('type')==='individual')>Individual</option><option value="department" @selected(request('type')==='department')>Department</option></select></label><label class="eims-filter-label">Status<select name="status" class="eims-filter-field"><option value="">All statuses</option>@foreach(['pending_receipt','active','rejected','returned'] as $status)<option value="{{ $status }}" @selected(request('status')===$status)>{{ ucfirst(str_replace('_',' ',$status)) }}</option>@endforeach</select></label><div class="flex gap-2 sm:col-span-3 sm:justify-end"><button class="eims-filter-button">Apply filters</button>@if(request()->hasAny(['search','type','status']))<a href="{{ route('assignments.index') }}" class="eims-filter-reset">Clear</a>@endif</div></form><a href="{{ route('assignments.create') }}" class="rounded-xl bg-gradient-to-r from-emerald-500 to-teal-600 px-5 py-2.5 text-center text-sm font-extrabold text-white shadow-lg">Prepare assignment</a></div>
        <div class="overflow-x-auto"><table class="min-w-full text-left text-sm"><thead class="bg-slate-50 text-[10px] font-bold uppercase tracking-wider text-slate-400"><tr><th class="px-6 py-4">Asset</th><th class="px-6 py-4">Recipient</th><th class="px-6 py-4">Prepared by</th><th class="px-6 py-4">Status</th><th class="px-6 py-4">Date</th><th></th></tr></thead><tbody class="divide-y divide-slate-100">
        @forelse($assignments as $assignment)<tr><td class="px-6 py-4"><p class="font-bold text-eims-ink">{{ $assignment->asset->name }}</p><p class="font-mono text-xs text-indigo-500">{{ $assignment->asset->asset_tag }}</p></td><td class="px-6 py-4"><p class="font-semibold">{{ $assignment->assignee?->name }}</p><p class="text-xs text-slate-400">{{ $assignment->location?->name }}</p></td><td class="px-6 py-4">{{ $assignment->assigner->name }}</td><td class="px-6 py-4"><span class="rounded-full bg-indigo-50 px-3 py-1 text-xs font-bold capitalize text-indigo-600">{{ str_replace('_',' ',$assignment->status) }}</span></td><td class="px-6 py-4 text-xs text-slate-400">{{ $assignment->assigned_at->format('d M Y, H:i') }}</td><td class="px-6 py-4 text-right"><a href="{{ route('assignments.show',$assignment) }}" class="font-bold text-indigo-600">View →</a></td></tr>@empty<tr><td colspan="6" class="px-6 py-16 text-center text-slate-400">No assignments found.</td></tr>@endforelse
        </tbody></table></div>@if($assignments->hasPages())<div class="border-t border-slate-100 p-5">{{ $assignments->links() }}</div>@endif
    </section>
</div>
@endsection
