@extends('layouts.app')
@section('title','Move asset · EIMS')
@section('heading','Request return or transfer')
@section('content')
<div class="mx-auto max-w-4xl"><div class="eims-card mb-6 p-6"><p class="font-mono text-xs font-bold text-indigo-500">{{ $asset->asset_tag }}</p><h2 class="mt-1 text-xl font-extrabold text-eims-ink">{{ $asset->name }}</h2><p class="mt-1 text-sm text-slate-400">Current custody remains active until the movement is fully confirmed.</p></div>
<form method="POST" action="{{ route('movements.store',$asset) }}" class="eims-card space-y-6 p-6" x-data="{type:'{{ old('type','transfer') }}',target:'{{ old('target_type','individual') }}',department:'{{ old('target_department_id') }}'}">@csrf
<div><label class="mb-2 block text-sm font-bold">Movement type</label><div class="grid gap-3 sm:grid-cols-2"><label class="rounded-xl border p-4"><input type="radio" name="type" value="transfer" x-model="type"> <strong>Transfer custody</strong><p class="ml-5 text-xs text-slate-400">Move to another officer or department.</p></label><label class="rounded-xl border p-4"><input type="radio" name="type" value="return" x-model="type"> <strong>Return to Procurement</strong><p class="ml-5 text-xs text-slate-400">Release custody back into stock.</p></label></div></div>
<div x-show="type==='transfer'" class="space-y-5 rounded-2xl bg-slate-50 p-5"><div><label class="mb-2 block text-sm font-bold">Destination custody</label><select name="target_type" x-model="target" class="w-full rounded-xl border-slate-200"><option value="individual">Individual officer</option><option value="department">Department</option></select></div><div><label class="mb-2 block text-sm font-bold">Destination department</label><select name="target_department_id" x-model="department" class="w-full rounded-xl border-slate-200"><option value="">Select department</option>@foreach($departments as $department)<option value="{{ $department->id }}">{{ $department->name }}</option>@endforeach</select><p class="mt-1 text-xs text-slate-400">Select the department first to keep the officer list relevant.</p></div><div x-show="target==='individual'"><label class="mb-2 block text-sm font-bold">Receiving officer</label><select name="target_user_id" class="w-full rounded-xl border-slate-200"><option value="">Select officer</option>@foreach($users as $user)<option value="{{ $user->id }}" x-show="department=='{{ $user->department_id }}'">{{ $user->name }} — {{ $user->staff_number }}</option>@endforeach</select></div><div x-show="target==='department'"><label class="mb-2 block text-sm font-bold">Authorized receiving officers</label><div class="max-h-56 space-y-2 overflow-y-auto rounded-xl border bg-white p-4">@foreach($users as $user)<label x-show="department=='{{ $user->department_id }}'" class="block text-sm"><input type="checkbox" name="receiver_ids[]" value="{{ $user->id }}"> {{ $user->name }} <span class="text-slate-400">({{ $user->staff_number }})</span></label>@endforeach</div><p class="mt-1 text-xs text-slate-400">Any selected officer may confirm receipt for the department.</p></div><div><label class="mb-2 block text-sm font-bold">Destination location</label><select name="target_location_id" class="w-full rounded-xl border-slate-200"><option value="">Select location</option>@foreach($locations as $location)<option value="{{ $location->id }}">{{ $location->name }}</option>@endforeach</select></div></div>
<div class="grid gap-5 sm:grid-cols-2"><div><label class="mb-2 block text-sm font-bold">Current condition</label><select name="condition_reported" class="w-full rounded-xl border-slate-200">@foreach(['excellent','good','fair','damaged'] as $condition)<option value="{{ $condition }}" @selected(old('condition_reported',$asset->condition)===$condition)>{{ ucfirst($condition) }}</option>@endforeach</select></div><div><label class="mb-2 block text-sm font-bold">Reason</label><textarea name="reason" rows="3" class="w-full rounded-xl border-slate-200" required>{{ old('reason') }}</textarea></div></div>
@if($errors->any())<div class="rounded-xl bg-red-50 p-4 text-sm text-red-700">{{ $errors->first() }}</div>@endif<div class="flex justify-end gap-3"><a href="{{ route('assets.show',$asset) }}" class="rounded-xl border px-5 py-3 text-sm font-bold">Cancel</a><button class="rounded-xl bg-gradient-to-r from-indigo-600 to-purple-700 px-6 py-3 text-sm font-extrabold text-white">Submit movement</button></div></form></div>
@endsection
