@extends('layouts.app')
@section('title',$movement->movement_number.' · EIMS')
@section('heading','Movement details')
@section('content')
<div class="mx-auto max-w-5xl space-y-6"><div class="eims-card p-6"><div class="flex flex-wrap justify-between gap-4"><div><p class="font-mono text-xs font-bold text-indigo-500">{{ $movement->movement_number }}</p><h2 class="mt-1 text-2xl font-extrabold text-eims-ink">{{ $movement->asset->name }}</h2><p class="text-sm text-slate-400">{{ $movement->asset->asset_tag }} · {{ $movement->asset->category->name }}</p></div><span class="h-fit rounded-full bg-indigo-50 px-4 py-2 text-xs font-bold capitalize text-indigo-600">{{ str_replace('_',' ',$movement->status) }}</span></div><dl class="mt-6 grid gap-4 border-t pt-5 sm:grid-cols-3"><div><dt class="text-xs uppercase text-slate-400">Type</dt><dd class="font-bold capitalize">{{ $movement->type }}</dd></div><div><dt class="text-xs uppercase text-slate-400">Requested by</dt><dd class="font-bold">{{ $movement->initiator->name }}</dd></div><div><dt class="text-xs uppercase text-slate-400">Reported condition</dt><dd class="font-bold capitalize">{{ $movement->condition_reported }}</dd></div>@if($movement->type==='transfer')<div><dt class="text-xs uppercase text-slate-400">Destination</dt><dd class="font-bold">{{ $movement->target_type==='individual' ? $movement->targetUser?->name : $movement->targetDepartment?->name }}</dd></div><div><dt class="text-xs uppercase text-slate-400">Location</dt><dd class="font-bold">{{ $movement->targetLocation?->name }}</dd></div>@endif</dl><div class="mt-5 rounded-xl bg-slate-50 p-4 text-sm"><strong>Reason:</strong> {{ $movement->reason }}</div></div>
@if(auth()->user()->hasPermission('assets.transfer') && $movement->status==='pending_procurement')<form method="POST" action="{{ route('movements.decision',$movement) }}" class="eims-card space-y-4 p-6">@csrf<h3 class="font-extrabold">Procurement decision</h3>@if($movement->type==='return')<div><label class="mb-2 block text-sm font-bold">Condition verified at return</label><select name="condition_confirmed" class="w-full rounded-xl border-slate-200">@foreach(['excellent','good','fair','damaged'] as $condition)<option value="{{ $condition }}">{{ ucfirst($condition) }}</option>@endforeach</select></div>@endif<textarea name="comments" required rows="3" placeholder="Decision reasons and handover instructions" class="w-full rounded-xl border-slate-200"></textarea><div class="flex gap-3"><button name="decision" value="approved" class="rounded-xl bg-emerald-600 px-5 py-3 text-sm font-bold text-white">{{ $movement->type==='return' ? 'Accept returned asset' : 'Approve transfer' }}</button><button name="decision" value="rejected" class="rounded-xl bg-red-50 px-5 py-3 text-sm font-bold text-red-700">Reject request</button></div></form>@endif
@if($movement->status==='awaiting_receipt' && $movement->receivers->contains(auth()->user()))<form method="POST" action="{{ route('movements.confirm',$movement) }}" class="eims-card space-y-4 p-6">@csrf<h3 class="font-extrabold">Confirm physical receipt</h3><p class="text-sm text-slate-500">Inspect the asset before confirming. Custody changes only after acceptance.</p><select name="condition_confirmed" class="w-full rounded-xl border-slate-200">@foreach(['excellent','good','fair','damaged'] as $condition)<option value="{{ $condition }}">{{ ucfirst($condition) }}</option>@endforeach</select><textarea name="comments" required rows="3" placeholder="Receipt observations" class="w-full rounded-xl border-slate-200"></textarea><div class="flex gap-3"><button name="decision" value="accepted" class="rounded-xl bg-emerald-600 px-5 py-3 text-sm font-bold text-white">Confirm receipt</button><button name="decision" value="rejected" class="rounded-xl bg-red-50 px-5 py-3 text-sm font-bold text-red-700">Reject handover</button></div></form>@endif
@if($movement->decision_comments)<div class="eims-card p-6"><h3 class="font-extrabold">Procurement feedback</h3><p class="mt-2 text-sm text-slate-600">{{ $movement->decision_comments }}</p></div>@endif @if($movement->confirmation_comments)<div class="eims-card p-6"><h3 class="font-extrabold">Receipt feedback</h3><p class="mt-2 text-sm text-slate-600">{{ $movement->confirmation_comments }}</p></div>@endif
</div>
@endsection
