<?php
namespace Tests\Feature;
use App\Models\Asset;
use App\Models\AssetAssignment;
use App\Models\AssetCategory;
use App\Models\AssetRequest;
use App\Models\Role;
use App\Models\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Support\Str;
use Tests\TestCase;
class AssetRequestWorkflowTest extends TestCase {
 use RefreshDatabase;
 public function test_normal_request_is_approved_allocated_and_fulfilled_only_after_receipt(): void {$this->seed();$admin=User::where('email','admin@eims.local')->first();$staff=$this->user('REQ-1','staff-member',$admin);$proc=$this->user('PROC-1','procurement-officer',$admin);$cat=AssetCategory::where('code','LAP')->first();$asset=Asset::create(['public_id'=>(string)Str::ulid(),'asset_category_id'=>$cat->id,'registered_by'=>$admin->id,'asset_tag'=>'EIMS-ICT-LAP-2026-800001','name'=>'Available Laptop','condition'=>'good','lifecycle_status'=>'in_stock','ownership_type'=>'purchased','currency'=>'TZS']);$this->actingAs($staff)->post(route('requests.store'),['asset_category_id'=>$cat->id,'purpose'=>'Research work','justification'=>'Required for field data analysis','properties'=>[['name'=>'Memory','value'=>'16GB']]])->assertSessionHasNoErrors();$request=AssetRequest::firstOrFail();$this->assertDatabaseHas('asset_request_properties',['asset_request_id'=>$request->id,'key'=>'memory','value'=>'16GB']);$this->actingAs($proc)->post(route('requests.decision',$request),['decision'=>'approved','comments'=>'Approved for research duties'])->assertSessionHasNoErrors();$this->actingAs($proc)->post(route('requests.allocate',$request),['asset_id'=>$asset->id])->assertSessionHasNoErrors();$assignment=AssetAssignment::firstOrFail();$this->assertSame('allocated',$request->fresh()->status);$this->actingAs($staff)->post(route('handovers.store',$assignment),['handed_over_by_user_id'=>$proc->id,'decision'=>'accepted','matches_expected_asset'=>1,'condition_received'=>'good'])->assertSessionHasNoErrors();$this->assertSame('fulfilled',$request->fresh()->status);$this->assertSame($staff->id,$asset->fresh()->custodian_user_id);}
 public function test_rejection_requires_feedback_and_does_not_create_assignment(): void {$this->seed();$admin=User::where('email','admin@eims.local')->first();$staff=$this->user('REQ-2','staff-member',$admin);$proc=$this->user('PROC-2','procurement-officer',$admin);$cat=AssetCategory::where('code','CHR')->first();$this->actingAs($staff)->post(route('requests.store'),['asset_category_id'=>$cat->id,'purpose'=>'Office seating','justification'=>'No chair currently assigned']);$request=AssetRequest::firstOrFail();$this->actingAs($proc)->post(route('requests.decision',$request),['decision'=>'rejected'])->assertSessionHasErrors('comments');$this->actingAs($proc)->post(route('requests.decision',$request),['decision'=>'rejected','comments'=>'Existing department stock must be checked first'])->assertSessionHasNoErrors();$this->assertSame('rejected',$request->fresh()->status);$this->assertDatabaseCount('asset_assignments',0);$this->assertDatabaseHas('notifications',['notifiable_id'=>$staff->id]);}
 private function user(string $staff,string $role,User $admin): User {$u=User::create(['public_id'=>(string)Str::ulid(),'staff_number'=>$staff,'name'=>$staff,'email'=>strtolower($staff).'@eims.local','status'=>'active','organizational_unit_id'=>$admin->organizational_unit_id,'primary_location_id'=>$admin->primary_location_id,'password'=>'Password123']);$u->roles()->attach(Role::where('slug',$role)->value('id'),['assigned_by'=>$admin->id,'assigned_at'=>now()]);return $u;}
}
