@extends('layouts.app')
@section('title','Register Officer')
@section('heading','Register officer')
@section('content')
<div class="mx-auto max-w-5xl pt-4"><form method="POST" action="{{ route('administration.users.store') }}" class="space-y-6">@csrf
@if($errors->any())<div class="rounded-xl border border-red-200 bg-red-50 px-5 py-4 text-sm text-red-700"><ul class="list-disc pl-5">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
<section class="eims-card p-6"><p class="text-xs font-bold uppercase tracking-wider text-indigo-500">Account</p><h2 class="mt-1 text-xl font-black text-eims-ink">Officer identity and access role</h2><div class="mt-6 grid gap-5 md:grid-cols-2">
@foreach([['name','Full name','text'],['staff_number','Staff number','text'],['email','Institutional email','email'],['phone','Phone number','text']] as [$field,$label,$type])<div><label class="text-sm font-bold text-slate-600">{{ $label }} @if($field!=='phone')*@endif</label><input type="{{ $type }}" name="{{ $field }}" value="{{ old($field) }}" @required($field!=='phone') class="mt-2 w-full rounded-xl border border-slate-200 px-4 py-3 text-sm"></div>@endforeach
<div><label class="text-sm font-bold text-slate-600">Role *</label><select id="role_id" name="role_id" required class="mt-2 w-full rounded-xl border border-slate-200 px-4 py-3 text-sm"><option value="">Select role</option>@foreach($roles as $role)<option value="{{ $role->id }}" data-role="{{ $role->slug }}" @selected(old('role_id')==$role->id)>{{ $role->name }}</option>@endforeach</select></div>
<div><label class="text-sm font-bold text-slate-600">Department *</label><select name="department_id" required class="mt-2 w-full rounded-xl border border-slate-200 px-4 py-3 text-sm"><option value="">Select department</option>@foreach($departments as $department)<option value="{{ $department->id }}" @selected(old('department_id')==$department->id)>{{ $department->name }}</option>@endforeach</select></div>
<div><label class="text-sm font-bold text-slate-600">Organizational unit</label><select name="organizational_unit_id" class="mt-2 w-full rounded-xl border border-slate-200 px-4 py-3 text-sm"><option value="">Not assigned</option>@foreach($units as $unit)<option value="{{ $unit->id }}" @selected(old('organizational_unit_id')==$unit->id)>{{ $unit->name }}</option>@endforeach</select></div>
<div><label class="text-sm font-bold text-slate-600">Primary location</label><select name="primary_location_id" class="mt-2 w-full rounded-xl border border-slate-200 px-4 py-3 text-sm"><option value="">Not assigned</option>@foreach($locations as $location)<option value="{{ $location->id }}" @selected(old('primary_location_id')==$location->id)>{{ $location->name }}</option>@endforeach</select></div>
<div></div><div><label class="text-sm font-bold text-slate-600">Temporary password *</label><input type="password" name="password" required class="mt-2 w-full rounded-xl border border-slate-200 px-4 py-3 text-sm"><p class="mt-1 text-xs text-slate-400">At least 12 characters with uppercase, lowercase and numbers.</p></div><div><label class="text-sm font-bold text-slate-600">Confirm password *</label><input type="password" name="password_confirmation" required class="mt-2 w-full rounded-xl border border-slate-200 px-4 py-3 text-sm"></div>
</div></section>
<section data-category-scope="maintenance-officer" class="eims-card hidden p-6"><p class="text-xs font-bold uppercase tracking-wider text-rose-500">Maintenance scope</p><h2 class="mt-1 text-lg font-extrabold text-eims-ink">Categories this officer may maintain</h2><p class="mt-1 text-xs text-slate-400">Only incidents in checked categories will be visible to this maintenance officer.</p><div class="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">@foreach($categories as $category)<label class="flex items-start gap-3 rounded-xl border border-slate-100 p-3 text-sm"><input type="checkbox" name="maintenance_categories[]" value="{{ $category->id }}" @checked(in_array($category->id,old('maintenance_categories',[])))><span><b class="text-eims-ink">{{ $category->name }}</b><small class="block text-slate-400">{{ $category->group->name }}</small></span></label>@endforeach</div></section>
<section data-category-scope="maintenance-review-officer" class="eims-card hidden p-6"><p class="text-xs font-bold uppercase tracking-wider text-cyan-500">Review scope</p><h2 class="mt-1 text-lg font-extrabold text-eims-ink">Categories this officer may review</h2><p class="mt-1 text-xs text-slate-400">Only maintenance submissions in checked categories will reach this review officer.</p><div class="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">@foreach($categories as $category)<label class="flex items-start gap-3 rounded-xl border border-slate-100 p-3 text-sm"><input type="checkbox" name="review_categories[]" value="{{ $category->id }}" @checked(in_array($category->id,old('review_categories',[])))><span><b class="text-eims-ink">{{ $category->name }}</b><small class="block text-slate-400">{{ $category->group->name }}</small></span></label>@endforeach</div></section>
<div class="flex justify-end gap-3"><a href="{{ route('administration.users.index') }}" class="rounded-xl border border-slate-200 px-5 py-3 text-sm font-bold text-slate-500">Cancel</a><button class="rounded-xl bg-gradient-to-r from-indigo-600 to-purple-700 px-6 py-3 text-sm font-extrabold text-white shadow-lg">Create officer account</button></div>
</form></div>
<script>(()=>{const select=document.getElementById('role_id'),sections=document.querySelectorAll('[data-category-scope]');function update(){const role=select.options[select.selectedIndex]?.dataset.role;sections.forEach(section=>section.classList.toggle('hidden',section.dataset.categoryScope!==role));}select.addEventListener('change',update);update();})();</script>
@endsection
