@extends('layouts.app')
@section('title','Confirm Handover')
@section('heading','Confirm property receipt')
@section('content')
<div class="mx-auto max-w-4xl pt-4"><form method="POST" action="{{ route('handovers.store',$assignment) }}" class="space-y-6">@csrf
@if($errors->any())<div class="rounded-xl border border-red-200 bg-red-50 px-5 py-4 text-sm text-red-700"><ul class="list-disc pl-5">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
<section class="eims-card p-6"><div class="flex items-start gap-4"><div class="grid size-14 place-items-center rounded-2xl bg-gradient-to-br from-indigo-600 to-purple-700 text-sm font-black text-white">{{ $assignment->asset->category->code }}</div><div><p class="font-mono text-xs font-bold text-indigo-500">{{ $assignment->asset->asset_tag }}</p><h2 class="mt-1 text-xl font-black text-eims-ink">{{ $assignment->asset->name }}</h2><p class="mt-1 text-sm text-slate-400">{{ $assignment->asset->category->group->name }} · {{ $assignment->asset->category->name }}</p></div></div><div class="mt-6 grid gap-4 border-t border-slate-100 pt-5 sm:grid-cols-3"><div><p class="text-[10px] font-bold uppercase text-slate-400">Expected condition</p><p class="mt-1 font-bold capitalize text-eims-ink">{{ $assignment->condition_at_issue }}</p></div><div><p class="text-[10px] font-bold uppercase text-slate-400">Receiving location</p><p class="mt-1 font-bold text-eims-ink">{{ $assignment->location->name }}</p></div><div><p class="text-[10px] font-bold uppercase text-slate-400">Prepared by</p><p class="mt-1 font-bold text-eims-ink">{{ $assignment->assigner->name }}</p></div></div>@if($assignment->accessories)<div class="mt-5 rounded-xl bg-slate-50 p-4"><p class="text-xs font-bold text-slate-400">Expected accessories</p><p class="mt-2 text-sm font-semibold text-eims-ink">{{ implode(', ',$assignment->accessories) }}</p></div>@endif</section>
<section class="eims-card p-6"><p class="text-xs font-bold uppercase tracking-wider text-emerald-500">Your verification</p><h2 class="mt-1 text-lg font-extrabold text-eims-ink">What did you actually receive?</h2><div class="mt-6 grid gap-5 md:grid-cols-2">
<div><label class="text-sm font-bold text-slate-600">Who handed it to you? *</label><select name="handed_over_by_user_id" required class="mt-2 w-full rounded-xl border border-slate-200 px-4 py-3 text-sm"><option value="">Select officer</option>@foreach($handoverUsers as $user)<option value="{{ $user->id }}" @selected(old('handed_over_by_user_id',$assignment->assigned_by)==$user->id)>{{ $user->name }} · {{ $user->staff_number }}</option>@endforeach</select></div>
<div><label class="text-sm font-bold text-slate-600">Condition received *</label><select name="condition_received" required class="mt-2 w-full rounded-xl border border-slate-200 px-4 py-3 text-sm">@foreach(['excellent','good','fair','damaged'] as $condition)<option value="{{ $condition }}" @selected(old('condition_received',$assignment->condition_at_issue)===$condition)>{{ ucfirst($condition) }}</option>@endforeach</select></div>
<fieldset><legend class="text-sm font-bold text-slate-600">Is this the expected property? *</legend><div class="mt-3 flex gap-4"><label class="flex items-center gap-2 rounded-xl border border-slate-200 px-4 py-3 text-sm font-bold"><input type="radio" name="matches_expected_asset" value="1" required @checked(old('matches_expected_asset')==='1')> Yes</label><label class="flex items-center gap-2 rounded-xl border border-slate-200 px-4 py-3 text-sm font-bold"><input type="radio" name="matches_expected_asset" value="0" required @checked(old('matches_expected_asset')==='0')> No</label></div></fieldset>
<fieldset><legend class="text-sm font-bold text-slate-600">Decision *</legend><div class="mt-3 space-y-2"><label class="flex items-start gap-3 rounded-xl border border-slate-200 p-3 text-sm"><input type="radio" name="decision" value="accepted" required @checked(old('decision')==='accepted')><span><b class="text-eims-ink">Accept</b><small class="block text-slate-400">Correct property and acceptable condition.</small></span></label><label class="flex items-start gap-3 rounded-xl border border-slate-200 p-3 text-sm"><input type="radio" name="decision" value="accepted_with_remarks" required @checked(old('decision')==='accepted_with_remarks')><span><b class="text-eims-ink">Accept with remarks</b><small class="block text-slate-400">Accept responsibility but record differences.</small></span></label><label class="flex items-start gap-3 rounded-xl border border-red-100 bg-red-50/40 p-3 text-sm"><input type="radio" name="decision" value="rejected" required @checked(old('decision')==='rejected')><span><b class="text-red-600">Reject handover</b><small class="block text-red-400">Wrong, damaged or unacceptable property.</small></span></label></div></fieldset>
<div class="md:col-span-2"><label class="text-sm font-bold text-slate-600">Receipt remarks</label><textarea name="remarks" rows="4" class="mt-2 w-full rounded-xl border border-slate-200 px-4 py-3 text-sm" placeholder="Required when accepting with remarks or rejecting">{{ old('remarks') }}</textarea></div>
</div></section><div class="flex justify-end gap-3"><a href="{{ route('handovers.pending') }}" class="rounded-xl border border-slate-200 px-5 py-3 text-sm font-bold text-slate-500">Cancel</a><button class="rounded-xl bg-gradient-to-r from-indigo-600 to-purple-700 px-6 py-3 text-sm font-extrabold text-white shadow-lg">Submit receipt confirmation</button></div>
</form></div>
@endsection
