@extends('layouts.app')
@section('heading','Request property')
@section('content')
<div class="mx-auto max-w-4xl pt-4"><form method="POST" action="{{ route('requests.store') }}" class="space-y-6">@csrf
@if($errors->any())<div class="rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-700">{{ $errors->first() }}</div>@endif
<section class="eims-standard-form"><header class="eims-form-heading"><h2>Property request information</h2><p>Provide the requested category, intended location and business need.</p></header><div class="mt-6 grid gap-5 md:grid-cols-2">
<label>Asset category *<select name="asset_category_id" required class="mt-2 w-full"><option value="">Select category</option>@foreach($categories->groupBy('group.name') as $group=>$items)<optgroup label="{{ $group }}">@foreach($items as $category)<option value="{{ $category->id }}" @selected(old('asset_category_id')==$category->id)>{{ $category->name }}</option>@endforeach</optgroup>@endforeach</select></label>
<label>Preferred location<select name="preferred_location_id" class="mt-2 w-full"><option value="">Use my primary location</option>@foreach($locations as $location)<option value="{{ $location->id }}" @selected(old('preferred_location_id')==$location->id)>{{ $location->name }}</option>@endforeach</select></label>
<label class="md:col-span-2">Purpose *<input name="purpose" value="{{ old('purpose') }}" required maxlength="500" class="mt-2 w-full" placeholder="State how the property will be used"></label>
<label class="md:col-span-2">Justification *<textarea name="justification" required rows="4" class="mt-2 w-full" placeholder="Explain why this property is required">{{ old('justification') }}</textarea></label>
</div></section>
<section class="eims-standard-form"><div class="flex justify-between gap-4"><header class="eims-form-heading flex-1"><h2>Preferred properties</h2><p>Optional requirements such as RAM, size, material or capacity.</p></header><button type="button" id="add" class="h-fit rounded-xl bg-indigo-50 px-4 py-3 text-sm font-bold text-indigo-600">Add property</button></div><div id="props" class="mt-5 space-y-3"></div></section>
<div class="flex justify-end gap-3"><a href="{{ route('requests.index') }}" class="rounded-xl border border-slate-200 px-5 py-3 text-sm font-bold text-slate-500">Cancel</a><button class="rounded-xl bg-gradient-to-r from-orange-500 to-red-500 px-6 py-3 text-sm font-bold text-white shadow-lg">Submit to Procurement</button></div></form></div>
<script>(()=>{let i=0;document.getElementById('add').onclick=()=>document.getElementById('props').insertAdjacentHTML('beforeend',`<div class="grid gap-3 rounded-xl border border-slate-200 bg-slate-50 p-4 sm:grid-cols-[1fr_1.5fr_auto] sm:items-end"><label>Property name<input name="properties[${i}][name]" pattern="[A-Za-z0-9 ]+" required class="mt-2 w-full" placeholder="e.g. RAM"></label><label>Preferred value<input name="properties[${i++}][value]" pattern="[A-Za-z0-9 ]+" required class="mt-2 w-full" placeholder="e.g. 16 GB"></label><button type="button" onclick="this.parentElement.remove()" class="rounded-xl px-3 py-3 font-bold text-red-500">Remove</button></div>`)})();</script>
@endsection
