@extends('layouts.app')
@section('title','Maintenance Case') @section('heading','Maintenance case')
@section('content')
<div class="mx-auto max-w-6xl space-y-6 pt-4">@if(session('success'))<div class="rounded-xl bg-emerald-50 px-5 py-3 text-sm font-bold text-emerald-700">{{ session('success') }}</div>@endif @if($errors->any())<div class="rounded-xl bg-red-50 px-5 py-3 text-sm text-red-600">{{ $errors->first() }}</div>@endif
<section class="eims-card p-6"><div class="flex flex-wrap items-start justify-between gap-4"><div><p class="font-mono text-xs font-bold text-indigo-500">{{ $case->asset->asset_tag }}</p><h2 class="text-2xl font-black text-eims-ink">{{ $case->asset->name }}</h2><p class="mt-1 text-sm text-slate-400">{{ $case->problem_summary }} · Reported by {{ $case->reporter->name }}</p></div><span class="rounded-full bg-indigo-50 px-4 py-2 text-xs font-bold capitalize text-indigo-600">{{ str_replace('_',' ',$case->status) }}</span></div><p class="mt-5 rounded-xl bg-slate-50 p-4 text-sm leading-6">{{ $case->problem_details }}</p></section>
@if(auth()->id()===$case->maintenance_officer_id && in_array($case->status,['assigned','spare_received'],true))<form method="POST" action="{{ route('maintenance.reports.store',$case) }}" class="eims-card p-6">@csrf<h3 class="font-extrabold text-eims-ink">Submit maintenance work report</h3><div class="mt-5 grid gap-4 md:grid-cols-2"><select name="technical_outcome" required class="rounded-xl border p-3"><option value="">Technical outcome</option>@foreach(['repaired','repair_in_progress','awaiting_spare','not_repaired','beyond_repair','no_fault_found'] as $o)<option value="{{ $o }}">{{ ucfirst(str_replace('_',' ',$o)) }}</option>@endforeach</select><fieldset class="flex gap-4 rounded-xl border p-3"><legend class="text-xs font-bold">Spare requirement</legend><label><input type="radio" name="spare_needed" value="0" required> No spare needed</label><label><input type="radio" name="spare_needed" value="1" required> Spare needed</label></fieldset><textarea name="findings" required rows="3" class="rounded-xl border p-3" placeholder="Inspection findings"></textarea><textarea name="work_performed" rows="3" class="rounded-xl border p-3" placeholder="Work performed"></textarea><textarea name="spare_description" rows="3" class="rounded-xl border p-3 md:col-span-2" placeholder="If spare is needed, describe every item and specification"></textarea></div><button class="mt-4 rounded-xl bg-rose-500 px-5 py-3 text-sm font-bold text-white">Send to Maintenance Review</button></form>@endif
@foreach($case->reports as $report)<section class="eims-card p-6"><div class="flex justify-between"><h3 class="font-extrabold text-eims-ink">Work cycle {{ $report->cycle_number }}</h3><span class="text-xs font-bold capitalize text-indigo-500">{{ str_replace('_',' ',$report->status) }}</span></div><p class="mt-3 text-sm"><b>Outcome:</b> {{ str_replace('_',' ',$report->technical_outcome) }}</p><p class="mt-2 text-sm">{{ $report->findings }}</p>
@if(auth()->user()->hasPermission('maintenance.review') && $report->status==='awaiting_review')<form method="POST" action="{{ route('maintenance.reviews.store',$report) }}" class="mt-5 grid gap-3 border-t pt-4 sm:grid-cols-[auto_1fr_auto]">@csrf<select name="decision" required class="rounded-xl border px-3"><option value="approved">Approve</option><option value="rejected">Reject</option></select><input name="comments" required class="rounded-xl border px-3 py-2" placeholder="Mandatory review comments"><button class="rounded-xl bg-cyan-600 px-4 py-2 text-sm font-bold text-white">Submit review</button></form>@endif
@if($report->spareRequisition) @php($req=$report->spareRequisition)<div class="mt-5 rounded-xl bg-amber-50 p-4"><p class="font-bold text-amber-800">Spare requisition {{ $req->requisition_number }} · {{ str_replace('_',' ',$req->status) }}</p><p class="mt-1 text-sm text-amber-700">{{ $req->requested_items }}</p>
@if(auth()->user()->hasPermission('maintenance.spares.procure') && $req->status==='pending_procurement')<form method="POST" action="{{ route('maintenance.spares.decision',$req) }}" class="mt-3 flex gap-2">@csrf<select name="decision" class="rounded-lg border px-2"><option value="approved">Approve</option><option value="rejected">Reject</option></select><input name="comments" required class="flex-1 rounded-lg border px-3" placeholder="Procurement comments"><button class="rounded-lg bg-amber-600 px-3 py-2 text-xs font-bold text-white">Decide</button></form>@endif
@if(auth()->user()->hasPermission('maintenance.spares.procure') && $req->status==='approved')<form method="POST" action="{{ route('maintenance.spares.issue',$req) }}" class="mt-3 flex gap-2">@csrf<input name="issued_items" required class="flex-1 rounded-lg border px-3" placeholder="Items actually issued"><input type="number" name="issued_quantity" min="1" required class="w-24 rounded-lg border px-3" placeholder="Qty"><button class="rounded-lg bg-emerald-600 px-3 py-2 text-xs font-bold text-white">Mark issued</button></form>@endif
@if(auth()->user()->hasPermission('maintenance.review') && in_array($req->status,['rejected','issued']) && !$req->relayed_at)<form method="POST" action="{{ route('maintenance.spares.relay',$req) }}" class="mt-3">@csrf<button class="rounded-lg bg-cyan-600 px-3 py-2 text-xs font-bold text-white">Relay Procurement decision to Maintenance</button></form>@endif
@if(auth()->id()===$case->maintenance_officer_id && $req->status==='issued' && $req->relayed_at && !$req->received_at)<form method="POST" action="{{ route('maintenance.spares.receive',$req) }}" class="mt-3 flex gap-2">@csrf<input name="receipt_remarks" required class="flex-1 rounded-lg border px-3" placeholder="Confirm items and condition received"><button class="rounded-lg bg-rose-600 px-3 py-2 text-xs font-bold text-white">Confirm Spare Receipt & Continue Repair</button></form>@endif</div>@endif</section>@endforeach
@if(auth()->id()===$case->maintenance_officer_id && in_array($case->status,['review_approved','review_rejected','procurement_rejected_relayed'],true))<form method="POST" action="{{ route('maintenance.finalize',$case) }}" class="eims-card p-6">@csrf<h3 class="font-extrabold">Finalize outcome for reporting officer</h3><div class="mt-4 grid gap-3 md:grid-cols-3"><select name="final_outcome" required class="rounded-xl border p-3"><option value="repaired">Repaired</option><option value="not_repaired">Not repaired</option><option value="beyond_repair">Beyond repair</option></select><input name="final_reason" required class="rounded-xl border p-3" placeholder="Final technical reason"><input name="collection_instructions" class="rounded-xl border p-3" placeholder="Collection instructions if repaired"></div><button class="mt-3 rounded-xl bg-rose-600 px-5 py-2 text-sm font-bold text-white">Notify reporting officer</button></form>@endif
@if(auth()->id()===$case->reported_by_user_id && $case->status==='ready_for_collection')<form method="POST" action="{{ route('maintenance.return',$case) }}" class="eims-card p-6">@csrf<h3 class="font-extrabold">Confirm repaired asset return</h3><div class="mt-4 grid gap-3 md:grid-cols-2"><input type="number" name="returned_by_user_id" required class="rounded-xl border p-3" placeholder="Returning officer user ID"><select name="condition_received" class="rounded-xl border p-3">@foreach(['excellent','good','fair','damaged'] as $c)<option>{{ $c }}</option>@endforeach</select><fieldset><label><input type="radio" name="correct_asset" value="1" required> Correct asset</label> <label><input type="radio" name="correct_asset" value="0"> Wrong asset</label></fieldset><input name="comment" class="rounded-xl border p-3" placeholder="Short receipt comment"></div><button class="mt-3 rounded-xl bg-emerald-600 px-5 py-2 text-sm font-bold text-white">Confirm receipt and close</button></form>@endif
</div>@endsection
